### ISSUE TITLE
json parser

### ISSUE THREAD

**Issue by jamesRUS52** [axibase/axibase-collector#148] opened 2018-10-23 13:30 UTC
Hi, I am triing to parse local json file and it works by test button but does not work on Run button

There are my logs and screenshots

2018-10-23 16:27:07,860;INFO;qtp424058530-1476;com.axibase.collector.service.job.JobExecutionServiceImpl;;;Scheduling job name: 'Power_JSON', id: 124 to run immediately
2018-10-23 16:27:07,864;INFO;qtp424058530-1476;com.axibase.collector.service.job.JobExecutionServiceImpl;;;Job name: 'Power_JSON', id: 124 successfully scheduled to run immediately
2018-10-23 16:27:07,880;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.job.JobExecutionServiceImpl;124;;Starting job id: 124, type: JSON
2018-10-23 16:27:07,881;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;org.springframework.batch.core.launch.support.SimpleJobLauncher;124;;Job: [FlowJob: [name=jsonJob]] launched with the following parameters: [{JOB_CONFIG_ID=124, JOB_CONFIG_TYPE=JSON, TIMESTAMP=1540301227856, configId=0, TEST_FLAG=false}]
2018-10-23 16:27:07,890;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.job.json.JsonPopulateJobConfigTasklet;124;;STEP 1 EXECUTED: 3
2018-10-23 16:27:07,896;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.job.TimeStepListener;124;;STEP '2' START [31955]
2018-10-23 16:27:07,936;INFO;taskExecutor-25;com.axibase.collector.service.job.TimeStepListener;124;1;STEP '2' START [31955]
2018-10-23 16:27:07,940;INFO;taskExecutor-25;com.axibase.collector.support.LimitedTaskExecutorWrapper;124;1;Limited task executor wrapper initialized with limit: 50
2018-10-23 16:27:07,945;INFO;taskExecutor-26;com.axibase.collector.service.sender.stub.DataServiceStub;124;1_1;Use STUB
2018-10-23 16:27:07,946;INFO;taskExecutor-26;com.axibase.collector.service.job.json.reader.JsonSimpleItemReader;124;1_1;JSON READER START
2018-10-23 16:27:07,946;ERROR;taskExecutor-26;com.axibase.collector.service.job.json.reader.JsonSimpleItemReader;124;1_1;Json process error
java.lang.NullPointerException: null
        at com.axibase.collector.service.job.json.reader.AbstractItemReader.getResponseInfo(AbstractItemReader.java:235)
        at com.axibase.collector.service.job.json.reader.AbstractItemReader.readItem(AbstractItemReader.java:136)
        at com.axibase.collector.service.job.json.reader.JsonSimpleItemReader.read(JsonSimpleItemReader.java:32)
        at com.axibase.collector.service.job.json.reader.JsonSimpleItemReader.read(JsonSimpleItemReader.java:12)
        at com.axibase.collector.service.job.json.reader.JsonItemReader.read(JsonItemReader.java:93)
        at com.axibase.collector.service.job.json.reader.JsonItemReader.read(JsonItemReader.java:27)
        at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy213.read(Unknown Source)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:157)
        at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:116)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:110)
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.axibase.collector.support.LimitedTaskExecutorWrapper$SemaphoreRunnable.run(LimitedTaskExecutorWrapper.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-10-23 16:27:07,965;ERROR;taskExecutor-26;com.axibase.collector.service.job.json.reader.JsonSimpleItemReader;124;1_1;Json reader error.
java.lang.NullPointerException: null
        at com.axibase.collector.service.job.json.reader.AbstractItemReader.readItem(AbstractItemReader.java:173)
        at com.axibase.collector.service.job.json.reader.JsonSimpleItemReader.read(JsonSimpleItemReader.java:32)
        at com.axibase.collector.service.job.json.reader.JsonSimpleItemReader.read(JsonSimpleItemReader.java:12)
        at com.axibase.collector.service.job.json.reader.JsonItemReader.read(JsonItemReader.java:93)
        at com.axibase.collector.service.job.json.reader.JsonItemReader.read(JsonItemReader.java:27)
        at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy213.read(Unknown Source)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:157)
        at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:116)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:110)
        at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.axibase.collector.support.LimitedTaskExecutorWrapper$SemaphoreRunnable.run(LimitedTaskExecutorWrapper.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-10-23 16:27:07,976;ERROR;taskExecutor-25;org.springframework.batch.core.step.AbstractStep;124;1;Encountered an error executing step jsonStepPartitionByEntity in job jsonJob
org.springframework.batch.core.JobExecutionException: Partition handler returned an unsuccessful step
        at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:112)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:139)
        at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:136)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-10-23 16:27:07,976;INFO;taskExecutor-25;com.axibase.collector.service.job.TimeStepListener;124;1;STEP '2' END [31955]: 40 ms
2018-10-23 16:27:07,978;ERROR;scheduler_Worker-19-JOB_CONFIG_ID=124;org.springframework.batch.core.step.AbstractStep;124;;Encountered an error executing step jsonStepPartitionByConfiguration in job jsonJob
org.springframework.batch.core.JobExecutionException: Partition handler returned an unsuccessful step
        at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:112)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
        at com.axibase.collector.service.job.JobExecutionServiceImpl.executeJob(JobExecutionServiceImpl.java:269)
        at sun.reflect.GeneratedMethodAccessor417.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy200.executeJob(Unknown Source)
        at com.axibase.collector.model.job.CollectorJob.execute(CollectorJob.java:55)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-10-23 16:27:07,978;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.job.TimeStepListener;124;;STEP '2' END [31955]: 82 ms
2018-10-23 16:27:07,984;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.sender.SenderUtil;124;;Send 1 commands to ATSD: http://*******.***:8088
2018-10-23 16:27:07,984;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.sender.stub.DataServiceStub;124;;Use STUB
2018-10-23 16:27:07,984;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;com.axibase.collector.service.sender.HttpBatchPutSender;124;;Batch[1] sent to ATSD: http://*******.***:8088
2018-10-23 16:27:07,986;INFO;scheduler_Worker-19-JOB_CONFIG_ID=124;org.springframework.batch.core.launch.support.SimpleJobLauncher;124;;Job: [FlowJob: [name=jsonJob]] completed with the following parameters: [{JOB_CONFIG_ID=124, JOB_CONFIG_TYPE=JSON, TIMESTAMP=1540301227856, configId=0, TEST_FLAG=false}] and the following status: [FAILED]
![4](https://user-images.githubusercontent.com/39707635/47364009-dfc44380-d6e0-11e8-9451-e641195bddb9.png)
![3](https://user-images.githubusercontent.com/39707635/47364011-dfc44380-d6e0-11e8-82e8-4035fde5730d.png)
![2](https://user-images.githubusercontent.com/39707635/47364012-dfc44380-d6e0-11e8-865e-022ba3e10a31.png)
![1](https://user-images.githubusercontent.com/39707635/47364013-e05cda00-d6e0-11e8-9522-976a2e7aeba8.png)

**Comment by rodionos** [comment] 2018-10-23 14:20
Greetings @jamesRUS52!

Thanks for raising the issue. The end of the log suggests that the commands are failing to make it to ATSD. Notice the following URL in the log file:

```
http://.:8088
```

Can you please check that the storage driver specified in the JSON job settings refers to the active and healthy ATSD configuration.

![image](https://user-images.githubusercontent.com/2098022/47367021-7eec3980-d6e7-11e8-9f5f-07e42d16df62.png)

Open JSON settings and click on plus icon to open the storage driver settings. Proceed by clicking Test. The result should be "Test passed".

If this fails to fix the problem, export the JOB in XML format. Check the XML file contents to remove any sensitive information since the attached file will be accessible to the public.

**Comment by rodionos** [comment] 2018-10-24 07:02
@jamesRUS52 - ok, makes sense. 

Could you also attach a sample `power.json` file so we can check if the problem is reproducible on our test instances?

I assume you're using the latest Collector version. The Revision-Number is displayed on Admin > Build Info page.

![image](https://user-images.githubusercontent.com/2098022/47412227-c9b39300-d773-11e8-983b-aebe184f271b.png)

**Comment by jamesRUS52** [comment] 2018-10-24 07:46
I have updated to latest version 20374 right now and the bug is still presents
this is my json file
[power.zip](https://github.com/axibase/axibase-collector/files/2509421/power.zip)

**Comment by rodionos** [comment] 2018-10-24 12:05
@jamesRUS52 - fixed in 20388

**Closed by rodionos** 2018-10-24 12:05 UTC
Labels: bug, done

**Comment by jamesRUS52** [comment] 2018-10-24 12:52
thanks a lot 
It works now
